# Generated by Django 5.0.4 on 2024-05-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scs', '0003_role_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
