# Generated by Django 5.0.4 on 2024-05-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scs', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
