# Generated by Django 5.0.4 on 2024-05-06 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scs', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_scs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='award',
            name='student',
        ),
        migrations.RemoveField(
            model_name='department',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='college',
            name='university',
        ),
        migrations.RemoveField(
            model_name='department',
            name='college',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='college',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='college',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='student',
        ),
        migrations.RemoveField(
            model_name='facultymember',
            name='department',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='educationalbackground',
            name='student',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='student',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='student',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='student',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='student',
        ),
        migrations.RemoveField(
            model_name='volunteeractivity',
            name='student',
        ),
        migrations.RemoveField(
            model_name='trainingworkshop',
            name='student',
        ),
        migrations.RemoveField(
            model_name='testscore',
            name='student',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scs.user_scs')),
            ],
        ),
        migrations.DeleteModel(
            name='AcknowledgementForm',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FacultyMember',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Funding',
        ),
        migrations.DeleteModel(
            name='Dissertation',
        ),
        migrations.DeleteModel(
            name='EducationalBackground',
        ),
        migrations.DeleteModel(
            name='Ethnicity',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.DeleteModel(
            name='VolunteerActivity',
        ),
        migrations.DeleteModel(
            name='TrainingWorkshop',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TestScore',
        ),
    ]
